### ISSUE TITLE
[Question] ThreshKnot implementation used in LinearTurboFold

### ISSUE THREAD

**Issue by waltergallegog** [LinearFold/LinearTurboFold#7]
Hello,
I have a simple question regarding the different ThreshKnot implementations available:
 - In the LTF paper, you mention as reference for ThreshKnot the following paper: _L. Zhang, H. Zhang, D. H. Mathews, L. Huang, ThreshKnot: Thresholded prob-knot for improved RNA secondary structure prediction. arXiv [Preprint] (2019)_. In this paper, it says: _ThreshKnot is available in the RNAstructure software package v6.2 (released November 27, 2019):https://rna.urmc.rochester.edu/RNAstructure.html_

- The [LinearPartition ](https://github.com/LinearFold/LinearPartition) package offers the option `--threshknot or -T` to get the threshknot structure

- In LinearTurboFold however, it seems to me threshknot has been implemented again, [here](https://github.com/LinearFold/LinearTurboFold/blob/main/src/probknot.cpp)

Could you confirm if those 3 implementations are equivalent, or has something been changed in the LTF implementation that could lead to better structures?

Thanks again
Walter.

**Comment by sizhen** [comment]
Hey Walter, 

LinearPartition and LinearTurboFold incorporate ThreshKnot to make sure the end-to-end runtime is linear with the sequence length. And yes, they are equivalent. The implementation in LinearTurboFold is the same as the one in RNAstructure. 

The prediction would be the same as long as the parameters of ThreshKnot are the same (threshold, the minimum length of the helix, and iterations). And the major parameter is the value of the threshold, the other two parameters wouldn't change the accuracy too much. 

Sizhen

**Comment by waltergallegog** [comment]
Thanks a lot for the clarification.
BR
Walter
